CREATE DATABASE Tetris;

CREATE TABLE Player (
	playerID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	userName VARCHAR(32) NOT NULL,
	passHash VARCHAR(64) NOT NULL
);

CREATE TABLE Score (
	scoreID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	score INT NOT NULL,
	datePlayed DATE NOT NULL,
	playerID INT NOT NULL,
	FOREIGN KEY (playerID) REFERENCES Player(playerID)
);

